###
GET http://localhost:3001/api/blog
# content-type: application/json
# Authorization: Bearer 
###
POST http://localhost:3001/api/blog
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3NTFiNTBhMWQ3ODcyNmFiYTNiMWMwYiIsImlhdCI6MTczMzQwODE1NX0.CaT9F2A4RaiyK0ekyTE-cQnN0O-SI0uZkGf-rGPGNSM

{
    "title": "Hi Herizon 2",
    "author": "User_Fang",
    "url":"123",
    "likes":5}

# 
###
DELETE http://localhost:3001/api/blog/6751b7041d78726aba3b1c21
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3NTFiNTBhMWQ3ODcyNmFiYTNiMWMwYiIsImlhdCI6MTczMzQxMjk5N30.fflksYMCjMkl8T-o6mqCFU07sOxsFGgQrSChp5SjVJk
###
PUT http://localhost:3001/api/blog/6751b7061d78726aba3b1c25
content-type: application/json
Authorization: Bearer 

{
    "title": "try to update",
    "author": "Fang",
    "url":"1234",
    "likes":500
}




###
POST http://localhost:3001/api/comments
Content-Type: application/json

{
  "content": "usercomment adding",
  "blog": "6749d7027ce927af6f1f37af"
}

###
POST http://localhost:3001/api/comments/6749d7027ce927af6f1f37af
Content-Type: application/json

{
  "content": "new comment API testing"
}
